FROM  ubuntu:latest

# Esse comando serve para executar comandos dentro de um container

ENTRYPOINT [ "echo", "Hello" ]

# Os comando executados pelo cmd sao mutaveis
CMD [ "world" ]

#docker run --rm iamrosada/ubuntu:latest 

#docker run --rm nginx bash -> ira rodar e sair
#docker run --rm -it nginx bash -> ira rodar e com interacao, sai com exit